### ISSUE TITLE
Handle GraphicProperties in BahnEditor

### ISSUE THREAD

**Issue by MechMK1** [MisterMarty/bahn-gz-editor#2]
The following GraphicProperties are implemented in BahnLib, but not used in BahnEditor:
- Smoke
- Steam
- Clock
- Cursor

Please implement.

**Comment by MisterMarty** [comment]
Added support for smoke and steam with commit 9b56fdd7484f36a53fbee96c2551ea6b426c165d

**Comment by MisterMarty** [comment]
Added support for clock with commit 012a926ad2a4c98ed7ffa4823e29057d2605646d
